#include "gfx.wayland.common.h"

#define WAYLAND_BACKEND_SOFTWARE 1
#define WAYLAND_BACKEND_OPENGL 2
#define WAYLAND_BACKEND_VULKAN 4

// NOTE: default wayland backend
#ifndef WAYLAND_BACKEND
#  define WAYLAND_BACKEND WAYLAND_BACKEND_OPENGL
#endif

#if WAYLAND_BACKEND & WAYLAND_BACKEND_SOFTWARE
#  error TODO
#endif
#if WAYLAND_BACKEND & WAYLAND_BACKEND_OPENGL
#  include "gfx.wayland.ogl.h"
#endif
#if WAYLAND_BACKEND & WAYLAND_BACKEND_VULKAN
#  error TODO
#endif
#if (WAYLAND_BACKEND & (WAYLAND_BACKEND_SOFTWARE|WAYLAND_BACKEND_OPENGL|WAYLAND_BACKEND_VULKAN)) == 0
#  error ERROR: unrecognized value for `WAYLAND_BACKEND`
#endif
